// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CreationController from "./creation_controller"
application.register("creation", CreationController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MemoEditController from "./memo_edit_controller"
application.register("memo-edit", MemoEditController)

import MemoSelectController from "./memo_select_controller"
application.register("memo-select", MemoSelectController)

import PlotBlockController from "./plot_block_controller"
application.register("plot-block", PlotBlockController)
